name: Build and Push to Dockerhub

on:
    push:
        branches: [ "main" ]

    # Allows action to be ran from github repo
    workflow_dispatch:

jobs:
    docker-build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # - name: Create Tag
            #   run: echo "tag=$(cat dockertag)" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.D_LOGIN }}
                password: ${{ secrets.D_PASS }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                # tags: $ {{ env.tag }} , gtrs15/discord.chatgpt:latest
                tags: gtrs15/chatgpt_discord:latest
                